### ISSUE TITLE
Does not play well with DelegateClass

### ISSUE THREAD

**Issue by uhoh-itsmaciek** [ohler55/oj#477]
I ran into an issue where Oj is not serializing a DelegateClass as I expected. I was able to minimize the test case to something pretty simple:

```ruby
require 'oj'
require 'json'

a = [1, 2, 3]

class MyArray < DelegateClass(Array); end

m = MyArray.new(a)

puts <<-EOF
JSON.generate:
       raw: #{JSON.generate(a)}
  delegate: #{JSON.generate(m)}

Oj.dump:
       raw: #{Oj.dump(a)}
  delegate: #{Oj.dump(m)}
EOF
```

the output is:

```
JSON.generate:
       raw: [1,2,3]
  delegate: [1,2,3]

Oj.dump:
       raw: [1,2,3]
  delegate: {"^o":"MyArray","delegate_dc_obj":[1,2,3]}
```

Is this expected? I expected Oj to behave like `JSON.generate` here. If this is intended, is there an option to mimic the `JSON` behavior? I looked through the docs but nothing stood out as relevant to me.

I ran into this working with Sequel's [pg_array](https://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pg_array_rb.html) extension which wraps `Array` via `DelegateClass`.
